### ISSUE TITLE
Infusion recipes not working.

### ISSUE THREAD

**Issue by LordPinkerton** [KryptonCaptain/Thaumic-Dyes#2]
Unable to make any infusion recipes for the mod except for Thaumium Robes. Infusion recipe has been triple checked and no items are damaged. Tried in creative and with all research unlocked via console command. Infusion ritual will just not initialize. 

This has been also tested with no mods other than Thaumcraft, Thaumic Dyes, Thaumcraft NEI Plugin, NotEnoughItems, and CodeChickenCore.

**Comment by LordPinkerton** [comment]
Okay, most of the issues I was having was because I didn't have Thaumic Upholstery loaded in as well. Didn't realize it was a dependency. 

However, now my issue is that certain recipes still aren't working. These are Ranger Armor, Reinforced Praetor set, Hardened Cultist set, Husk set, and faceplates. Is this an issue or am I missing some other prerequisite besides the research?

**Comment by KryptonCaptain** [comment]
First off, T.Upholstery isn't a dependency. Technically, it's listed as "Incompatible" due to how we had early versions of the T.Dyes code setup, but I can't personally change or remove that on Curse.

Somehow, once again, this is a case of it works/doesn't work and I have no idea why. The code for registering the recipes/research is exactly the same for all items, so I'm rather puzzled what would be causing it. I'll look over it

**Comment by LordPinkerton** [comment]
I appreciate you looking into this.

**Comment by DEX47** [comment]
I'm attempting to craft the Iron Fortress Helmet. My setup is 100% however the it does not trigger when activated. Will get to more testing when I can.

**Comment by LordPinkerton** [comment]
Verify you're using version 1.5.1 of Thaumic Dyes and that the armor in the center is undamaged. Just tested and it' appears to be working correctly. What mods do you have loaded?

**Comment by DEX47** [comment]
I have a bit of a list as far as mods go; All but 2 are 1.7.10

2.4.115- Ancient Warfare 2 (by shadowmage45)
1.0.9- Fluxed-Core (by jaredlll08)
1.0.5- ContentTweaker (by jaredlll08)
1.4.294- ElecCore | Rendering Library (by Elec332)
1.8.1- McJtyLib (by McJty)
1.1.4- Deep Resonance (by McJty)
4.2.16.64- Forestry (by SirSengir)
0.7.7- Immersive Engineering (by BluSunrize)
091- Enchiridion (by joshiejack)
1.2.4.2a- Mariculture (by joshiejack)
9.12.2.0- Railcraft (by CovertJaguar)
2.8.1-174- Minefactory Reloaded (by skyboy026)
4.1.4-247- Thermal Expansion (by TeamCoFH)
1.2.5-115- Thermal Foundation (by TeamCoFH)
1.2.0-171- Thermal Dynamics (by TeamCoFH)
4.23- RFTools (by McJty)
0.9.1- OpenModsLib (by OpenMods)
0.8- Sound Filters (by Tmtravlr)
1.75- ComputerCraftEdu (by dantwohundred)
1.1-53- Thaumic Exploration (by nekosune)
0.82- CrayTokens Lite (by Paint_Ninja)
1.1.0- Better Boat (by SanAndreasP)
1.0.5.6- Dynamic Surroundings (by OreCruncher)
a- Pam's Harvest the Nether (by MatrexsVigil)
1.0.4- Waystones (by BlayTheNinth)
1.1.6- Waila Harvestability (by squeek502)
1.8.8- Tinkers Construct (by mDiyo)
1.0.7.47- CodeChickenCore (by chicken_bones)
0.3.2b- Mantle (by mDiyo)
2.3.6.1- DecoCraft2 (by RazzleberryFox)
1.2.7- Grimoire of Gaia 3(by Silentine)
0.11.1.109- Modular Powersuits (by MachineMuse)
1.3.2- Hopper Ducts (by FyberOptic)
1.2.4- AnimationAPI (by thehippomaster21)
4.7.0pre12.95- Project Red - World (by Mr_TJP)
1.5.1- OpenBlocks (by OpenMods)
1.11.5 BiblioCraft (by JDSinclair)
1.4.6- ExtraTiC (by JeanGlassmaker)
2-0.9.6- ModTweaker (by jaredlll08)
1.1.0.11- MineTweaker RecipeMaker (by DoubleDoorDevelopment)
2.2.1- Lava Monsters (by docrobb)
1.3- Ice Shards (by ljfa)
0.14.3- MalisisCore (by Ordinastie)
r7.6- Tainted Magic (by yorkeMC)
0.12.0- Alternate Terrain Generation (by TTFTCUTS)
0.28.2- Automagy (by Tuhljin)
1.0.0-5- Elsewhere Border (by TehNut)
_1.7.2-2A- Thaumcraft Mob Aspects (by Parker8283)_
1.0.3b- Exotic Birds (by Pavoreality)
3.3.8.1- Carpenter's Blocks (by Syntaxial)
2.3.7- The Twilight Forest (by Benimatic)
1.23- FastCraft (by Player)
4.2.3.5- Thaumcraft (by azanor)
_1.7.2-0.7- UndergroundBiomesConstructs (by Zeno410)_
1.1.1- Storage Drawers: Biomes O' Plenty Pack (by jaquadro)
0.2.9.4- UBC Ore Registrar (by marwat208)
1.1.28- Refined Relocation (by Dynious)
3.2.2- Special Mobs (by docrobb)
1.1- Clock HUD (by QKninja)
4.0.4.18- Metallurgy Core (by JeanGlassmaker)
1.3.1- Scott's Tweaks (by scottkillen)
4.7.0pre12.95- Project Red - Base (by Mr_TJP)
1.75- ComputerCraft (by dantwohundred)
1.16.6- Traveller's Gear (by BluSunrize)
2.16.1- Gravestone (by NightKosh)
2.0.14- Better Foliage (by octarine_noise)
1.3.2- Kore Sample (by scottkillen)
1.8.6- Hardcore Ender Expansion (by chylex)
1.0.5- CraftTweaker (by jaredlll08)
1.1.10- Witching Gadgets (by BluSunrize)
1.1.7b- Runic Dungeons (by MrComputerGhost)
2.5.6-10- Reptile Mod (by crackedEgg)
b- Pam's Clay Spawn (by MatrexsVigil)
1.5.10- Waila (by ProfMobius)
1.10.8- Storage Drawers (by jaquadro)
2.1.1- Mo' Zombies! (by Coocoo617)
1.11- Nomadic Tents (by sky_01)
1.0.4.187- Bookshelf (by darkh4x)
4.0.6.80- Metallurgy (by JeanGlassmaker)
1.13.2- MalisisDoors (by Ordinastie)
1.4.0.009- Ars Magica 2 (by Torarion)
0.4.1.104- Numina (by MachineMuse)
r03- StartingInventory (by bspkrs)
1.5.0b- Roguelike Dungeons (by Greymerk)
1.4- FastLeafDecay (by Olafskii)
1.5.2- Glass Shards (by ljfa)
0.24.1- Witchery (by Emoniph)
1.5.0- AgriCraft (by InfinityRaider)
15.26.1a- Expanded Industry (by Draco18s)
r1.8-249- Botania (by Vazkii)
1.0.0-5- EnviroMine (by Funwayguy)
1.4.1.9- WR-CBE-Universal (by chicken_bones)
0.575- Forbidden Magic (by Assassinfox)
Lb- Pam's HarvestCraft (by MatrexsVigil)
4.7.0pre12.95- Project Red - Integration (by Mr_TJP)
1.59-dev-152- Inventory Tweaks (by Kobata)
3.1.3-327- CoFH Core (by TeamCoFH)
1.2.12- Extra Utilities (by RWTema)
1.0.7.3- Gadomancy (by makeoo)
6.1.1- WorldEdit (by sk89q)
10.13.4.1566- WorldEditCUI Forge Edition (by hexosse)
1.1.9- Thaumic Horizons (by TheKentington)
**1.5.1-0- Thaumic Dyes (by amerem)**
0.2.7- Arcane Engineering (by thatguy3039)
1.1.3- Sonar Core (by Ollie_Lansdell)
0.2.4- Practical Logistics (by Ollie_Lansdell)
2.9.5.11- Chisel (by tterrag1098)
0.8c- Adventure Backpack (by JavierDarkona)
1.11.3- SG Craft (by gcewing)
2.2.9-232- OpenModularTurrets (by Poenjabiesous)
1.0- MattDahEpic Core (MDECore) (by MattDahEpic)
1.0.0-132- Collective Framework (by austinv11)
1.3.1- Auto Ore Dictionary Converter (by MattDahEpic)
1.21- Compact Machines (by Davenonymous)
1.3.6- Peripherals++ (by austinv11)
2.0.4- Catwalks 2 (by thecodewarrior1)
1.1.0- Big Doors (by jaquadro)
0.4.3A- Big Reactors (by ErogenousBeef)
0.1.12- LibVulpes (by zmaster587)
1.0.4- Advanced Rocketry (by zmaster587)
1.0.5.120- NotEnoughItems (by chicken_bones)

**Comment by LordPinkerton** [comment]
That's quite the list. Is this a modpack? If so, please link it and I'll try and figure out whats going on. If I had to guess, one of those mods is replacing or modifying the infusion components, probably the armor, from the vanilla one.

**Comment by DEX47** [comment]
It's my own server build. My thoughts are the Ars Magica 2 metadata for the infusion and armor XP. I was going to start with that as my base to work on testing.

**Comment by LordPinkerton** [comment]
Never had a problem with Ars, but might be worth taking it out and seeing what happens. Might want to also check your character profile that has the armor in his inventory with NBTExplorer and see what additional data is being added to the item.

**Comment by DEX47** [comment]
Oh interesting find. There is something else going on here, it maybe an update outside of Thaumic Dyes. Roll back a version two on my server to test. I'll let you know.

**Comment by KryptonCaptain** [comment]
- "Thaumic Dyes (by amerem)"

You're killing me here.

As @LordPinkerton mentioned, check you're on the latest version of T.Dyes first. The infusion works with Dyes as a standalone mod, so if something else is changing the properties of one of the material components, it might cause issues.
For future reference though, listing mods and authors doesn't actually help that much without knowing the versions of each mod.

**Comment by DEX47** [comment]
Well that makes me wish curse added version numbers to the mod export list. Updated post with verions for you and yes 1.5.1 is on my server.

I plan to do more tests and look at where the issue started between my server build updates. Figured it may help with more targeted feedback. However my time for testing is limited as I'm relocating to a new state. What I did discover on my current live build was;

Using the creative default silver-wood wand.

Ranger Chest infusion succeeded
Traveler boots infusion succeeded
Iron Fortress Helmet infusion failed
Infusion Alter creation failed
Creating the Thaumonomicon succeeded

This is showing me there is more investigation needed before I can determine what all is going on here. What I can say for sure is that the latest major update I had seems to be what brought about this issue. and that involved:

**Updated mods:**
-Modular Powersuits 0.11.1.107
-Numina 0.4.1.103
**Added mods:**
-Advanced Rocketry 1.0.3
-Big Doors 1.1.0
-Big Reactors 0.4.3A
-Catwalks 2 2.0.4
-Tubestuff 59.0.4
-Peripherals++ 1.3.6
-Compact Machines 1.12
-Auto Ore Dictionary Converter 1.3.1

I'm still needing more time to gather and test a build deconstruction but if you know something offhand with just the version number on my mod list, that would be great news. If not then I'll continue to dig and get you my build version changes and tests to narrow down at what point things break on my server. However I won't have time to dig into this too deeply for another two weeks.

The current build update brought in the following patches:

**Updated mods:**
-Decocraft  from 2.3.5 to 2.3.6
-StorageDrawers from 1.10.7 to
-Thaumic Dyes from 1.5.0-1 to 1.5.1-0
-OpenModularTurrets from 2.2.5-226 to 2.2.9-232
-Numina from 0.4.1.103 to 0.4.1.104
-ModularPowersuits from 0.11.1.107 to 0.11.1.109
-Advanced Rocketry from 1.0.3 to 1.0.4
-LibVubes from 0.1.11 to 0.1.12

I'm sure there are dependencies thrown into the mix by curse as well that I haven't even looked at. Hope some of this is useful to you. Will do more when I can.

**Comment by LordPinkerton** [comment]
You don't have a lot of Thaumcraft addons in your pack, and the ones you do have are pretty stable, so I don't think any of them are your problem. If you want, I can give this a little hands on checking myself, but I'd need you to compile your modpack and host it somewhere so I can download it. It'd be best if you use the Curse export function, so you can minimize the size of the download. Other than that, all I'd be able to suggest is double check your blocks and crafting items, use NEI to dump block and item info, and verify that none of the affected items are being changed by another mod. With the amount of mods you have in your pack, there are bound to be more breaking interactions that you probably haven't noticed yet. Speaking from experience, a modpack the size you've compiled might take weeks to finally iron out all the issues.

**Comment by KryptonCaptain** [comment]
Reopening this because I just ran into this issue on a server.
Gonna look into it.
