### ISSUE TITLE
Iron fortress uncraftable on servers

### ISSUE THREAD

**Issue by KryptonCaptain** [KryptonCaptain/Thaumic-Dyes#4]
As per #2 , which makes no sense, since the recipe code is all the same.

**Comment by DEX47** [comment]
Just stumbled on an an issue testing Thaumic Dyes 1.6.0. When in creative (all research) mode I was able to craft the Iron Fortress Armor.

I then discovered I was still unable to craft this outside of creative having the Iron Fortress Armor research completed. I then decided to finish the Enhanced Fortress Armor research. I was surprised to see I could now craft the Iron Fortress Armor. 

Seems there is a dependency pointing to the wrong research requirement.

**Comment by KryptonCaptain** [comment]
You were 100% correct. I can see how that happened, and it was really easy to miss.
Will be fixed in next build

**Comment by KryptonCaptain** [comment]
Fixed. New release soon.
