### ISSUE TITLE
Runic Shielding Upgrade Prices

### ISSUE THREAD

**Issue by Dayyer1** [KryptonCaptain/Thaumic-Dyes#5]
I noticed you wanted feedback on the infusion altar essentia recipes.
I'll have to look at them again later, but at first glance, that seemed like a lot of essentia for the upgrades. Like, 512 potenia.
That's... quite a bit. I'm afraid I don't have that much laying around.
That specific upgrade is indeed powerful (if I remember correctly. Not currently at my computer.) but I feel that the prices are too darn high.
Plus, do the upgrades stack? Can you apply the same upgrade twice to one piece of armor so that you can get a more powerful upgrade?
And for the enhanced runic shielding armor, would two upgrades apply at the same time if you put them on, or do you have to toggle which one works?
I don't quite understand the entry.
Also, I apologize if this is the wrong place for questions. I wasn't sure where to go.

**Comment by KryptonCaptain** [comment]
That particular upgrade adds 50% extra points of shielding, which ranges from a +4 boost to +12, depending on the piece's base amount. 
The essentia cost is the same as taking a normal armour piece from +4 to +5 shielding, which you can see in the vanilla TC entry for Runic Augmentation - so it feels fair to me, considering that the output is much greater. If anything, it's not enough in my opinion.
It's not supposed to be cheap.

You can't stack/increase the level of the upgrade on a single part. It evaluates how many of that upgrade you have in total across all parts. Some of the effects scale based on that total.
For Enhanced, both augments apply at the same time.

I'll look into writing a more clear entry though.

**Comment by Dayyer1** [comment]
Ah, I see. I didn't think about that. I see how the prices are more reasonable now.
