### ISSUE TITLE
Random crash when taking damage. [TD 1.8.5]

### ISSUE THREAD

**Issue by 63502** [KryptonCaptain/Thaumic-Dyes#6]
After I grabbed the update with the Runic armor, I started getting this crash at random. It seem to happen most often whenever I am on fire or taking fire damage. From what I could glean from the crash log, it has something to do with the runic armor rendering when the player gets hurt(don't quote me on that though).

[Crash Log on Gist](https://gist.github.com/63502/e052c64dc8b3b197919092592b4d1739)

**Comment by KryptonCaptain** [comment]
Can you list which armour parts you had equipped and upgrades they had, if applicable?

**Comment by 63502** [comment]
This is actually the strangest part. It doesn't matter if have runic armor on when this happens. In my survival world where that crash log comes from, I don't even have the infusion altar research yet.

**Comment by KryptonCaptain** [comment]
Sometimes code behaves differently between dev version and "live" version.
I'll get on this as soon as I'm able, as it's a pretty major bug

**Comment by 63502** [comment]
Ok, cool.

**Comment by 63502** [comment]
Not sure that this is necessary at this point, but I just managed to get the same crash while fighting a spider in my survival world. I still do not have the runic armor or the research for runic armor. At this point, I think this can happen whenever the player takes damage.

[Crash Log 2 Gist](https://gist.github.com/63502/8d1985aa6fc7c510930a020c43670722)

**Comment by KryptonCaptain** [comment]
Should be fixed on latest build. Will be available soon.

**Comment by 63502** [comment]
Ok, good. I just had to MCEdit out a glitched spider that crashed my world on startup because of that bug. I'm glad to hear that the fix went ok, and I'll be testing out the new build as soon as I get it.
